function preloader()
{
	//array to store images names
	const imagesList = ["sol1.jpg","sol2.jpg","sol3.jpg"];


	//empty array
	const images=[]

	for(let i=0;i<imagesList.length;i++)
	{
		images[i]=new Image();
		images[i].src = imagesList[i];
	}

	console.log(`preloaded images :\n\t${images[0].src}\n\t${images[1].src}\n\t${images[2].src}`);
};
window.addEventListener("load",preloader);


//nodelist for buttons
const tabbuttons = document.querySelectorAll(".tabbutton");

//object with subobjects
const ro =  
{
	tab1:{
		headingContent:"Biomass",
		bodyText:"Biomass power plants generate energy by burning wood waste, sawdust, and burning organic agricultural waste. While burning of these materials produces greenhouse gases, the emissions are significantly lower than those produced by oil-based fuels.",
		imgUrl:"sol1.jpg",
		imgAlt:"image of sol 1"
		},
	tab2:{
		headingContent:"Geothermal Energy",
		bodyText:"This kind of green energy makes use of thermal energy stored just beneath the earth's crust.Geothermal energy was utilized for a long time to bath in hot springs, and the same energy may be used to power turbines and generate electricity.",
		imgUrl:"sol2.jpg",
		imgAlt:"image of sol 2"
		},
	tab3:{
		headingContent:"Hydropower",
		bodyText:"This sort of green energy, also known as hydroelectric power, generates electricity by using the flow of water in rivers, streams, dams, and other water bodies. Hydropower can even be generated on a small scale by running water through tubes in the home, or it can be generated by evaporation, precipitation, or marine waves.",
		imgUrl:"sol3.jpg",
		imgAlt:"image of sol 3"
		}
	


}
//html container reference
let tb = document.getElementById("tabcontent1");

//add content on load 
tb.getElementsByClassName('tabhead')[0].innerHTML=`<h1>${ro.tab1.headingContent}</h1>`;
tb.getElementsByClassName('conimg')[0].innerHTML=`<img src="${ro.tab1.imgUrl}" alt="${ro.tab1.imgAlt}">`;
tb.getElementsByClassName('context')[0].innerHTML=`<p>${ro.tab1.bodyText}</p>`;


function handleSelection()
{
	//check all buttons of tabs for id active buttons,if found remove then add id to clicked button
	for(let j =0;j<tabbuttons.length;j++)
	{
		if(tabbuttons[j].hasAttribute('id'))
		{
			tabbuttons[j].removeAttribute("id");
			this.setAttribute('id',"active-button");
			var activetab = this.getAttribute('href');
			//this upper line use to find which button is clicked with help 
			
			//conditions to put data according to clicked button
			if(activetab=="#tabcontent2")
			{
				tb.getElementsByClassName('tabhead')[0].innerHTML=`<h1>${ro.tab2.headingContent}</h1>`;
				tb.getElementsByClassName('conimg')[0].innerHTML=`<img src="${ro.tab2.imgUrl}" alt="${ro.tab1.imgAlt}">`;
				tb.getElementsByClassName('context')[0].innerHTML=`<p>${ro.tab2.bodyText}</p>`;
			}
			else if(activetab=="#tabcontent1")
			{
				tb.getElementsByClassName('tabhead')[0].innerHTML=`<h1>${ro.tab1.headingContent}</h1>`;
				tb.getElementsByClassName('conimg')[0].innerHTML=`<img src="${ro.tab1.imgUrl}" alt="${ro.tab1.imgAlt}">`;
				tb.getElementsByClassName('context')[0].innerHTML=`<p>${ro.tab1.bodyText}</p>`;
			}
			else if(activetab=="#tabcontent3")
			{
				tb.getElementsByClassName('tabhead')[0].innerHTML=`<h1>${ro.tab3.headingContent}</h1>`;
				tb.getElementsByClassName('conimg')[0].innerHTML=`<img src="${ro.tab3.imgUrl}" alt="${ro.tab3.imgAlt}">`;
				tb.getElementsByClassName('context')[0].innerHTML=`<p>${ro.tab3.bodyText}</p>`;
			}
			else
			{
				alert('no tab selected')
			}

		}
		
	}
}
for (let k = 0; k < tabbuttons.length; k++) {
    tabbuttons[k].addEventListener("click", handleSelection);
}




